### ISSUE TITLE
check_snmp_storage and 5% reserved space on local FS

### ISSUE THREAD

**Issue by emi65** [SteScho/manubulon-snmp#36]
Nagios core 4.2.1 and check_snmp_storage Ver. 1.3.3
The check is available on Nagiosexchange web site

The check_snmp_storage has -R option in order to sum 5% space to %occupied space
The rule should be applie only to ext2 and ext3 FS but the script sum this 5% to NFS FS
This is the error

Someone could be fix the problem
Regards and Thanks
Emilio

**Comment by dnsmichi** [comment]
Do you have an exact url where this project is linked on nagios exchange? I've never uploaded it there, I don't care about Nagios.

Further, try the git master and post your exact cli command and results including a full verbose output.

**Comment by SteScho** [comment]
Since the last message was a while ago and I'm currently cleaning up: Closed.

A quick note: If you think you should add the root reserved blocks to free, then simply just set these spare to 0% - my opinion.
