### ISSUE TITLE
SNMP interface check doesn't work with Perl < 5.13.2

### ISSUE THREAD

**Issue by miken32** [SteScho/manubulon-snmp#63]
## Current Behavior
Commit 9f9b15a added a bunch of string replacements using the `/r` modifier which is only available in versions of Perl since 5.13.2. Other versions (like those still in use by RHEL6) will complain with "Bareword found where operator expected."

## Possible Solution
Find a different method of escaping dots. If this is needed, there are a dozen other ways to do it that would not break backward compatibility.

## Your Environment
check_snmp_int version : 2.1.0
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
Scientific Linux release 6.9 (Carbon)

**Comment by dnsmichi** [comment]
I don't mind using a different solution here. Can you send a PR?
